name: pinterest_app_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.6.1

  # for design
  cupertino_icons: ^1.0.2

  # for connect network
  http_interceptor: ^1.0.2
  http: ^0.13.4

  #image
  cached_network_image: ^3.2.1

  get: ^4.6.5
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
